;;; cargo-transient-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from cargo-transient.el

 (autoload 'cargo-transient "cargo-transient" nil t)
(register-definition-prefixes "cargo-transient" '("cargo-transient-"))

;;; End of scraped data

(provide 'cargo-transient-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cargo-transient-autoloads.el ends here
