;;; pug-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from pug-mode.el

(autoload 'pug-mode "pug-mode"
"Major mode for editing Pug files.

\\{pug-mode-map}

In addition to any hooks its parent mode `prog-mode' might have run,
this mode runs the hook `pug-mode-hook', as the final or penultimate
step during initialization." t)
(autoload 'pug-compile "pug-mode"
"Compile the current pug file into html, using pug-cli.

If the universal argument is supplied, render pretty HTML (non-compressed).

(fn &optional ARG)" t)
(add-to-list 'auto-mode-alist '("\\.\\(?:jade\\|pug\\)\\'" . pug-mode))
(register-definition-prefixes "pug-mode" '("pug-"))

;;; End of scraped data

(provide 'pug-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pug-mode-autoloads.el ends here
