n = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"
j = "search_next"
k = "move_next_word_end"
l = "insert_mode"
J = "search_prev"
K = "move_next_long_word_end"
L = "insert_at_line_start"
"C-n" = "goto_next_diag"
"C-e" = "goto_prev_diag"
"A-h" = "swap_view_left"
"A-i" = "swap_view_right"
"A-n" = "swap_view_down"
"A-e" = "swap_view_up"
"C-A-left" = "swap_view_left"
"C-A-right" = "swap_view_right"
"C-A-up" = "swap_view_up"
"C-A-down" = "swap_view_down"
"C-A-h" = "swap_view_left"
"C-A-i" = "swap_view_right"
"C-A-e" = "swap_view_up"
"C-A-n" = "swap_view_down"
E = "hover"
