use std::path::{Path, PathBuf};
use std::sync::Arc;

pub mod backends;
pub mod bump;
pub mod chezmoi;
pub mod chezmoi_client;
pub mod config;
pub mod container;
pub mod error;
pub mod executor;
pub mod feature;
pub mod feature_store;
pub mod fs;
pub mod hooks;
pub mod installer;
pub mod manifest;
pub mod merge;
pub mod nix_feature_cache;
pub mod os;
pub mod paths;
pub mod plan;
pub mod progress;
pub mod runtime;
pub mod setup;
pub mod sync_backend;
pub mod toolchain;

pub use backends::{NixSyncBackend, UptSyncBackend};
pub use chezmoi::{ModifiedFile, RemoveFilesReport};
pub use chezmoi_client::{ChezmoiClient, NoopChezmoiClient, SourceBackup};
pub use config::{
    DotfilesConfig, FeatureSelection, UserConfig, UserSettings, CURRENT_SCHEMA_VERSION,
    DEFAULT_DOTFILES_SOURCE,
};
pub use container::{ContainerCleaner, NoopContainerCleaner};
pub use error::KaizenError;
pub use executor::{NoopExecutor, ProcessCommand, ProcessExecutor, ProcessOutput};
pub use feature::FeatureFile;
pub use feature_store::FeatureStore;
pub use fs::FileSystem;
pub use hooks::HookRunner;
pub use installer::{Installer, PackageInstaller, Remover, Updater};
pub use os::{PackageManagerKind, TargetOs};
pub use paths::PathProvider;
pub use plan::{ConfigPlan, HookPlan, InstallPlan, WorkflowPlan};
pub use progress::{NoopReporter, ProgressReporter};
pub use runtime::Runtime;
pub use setup::{
    render_config, resolve_features_dir_from_source, BootstrapStatus, ChezmoiBootstrapper,
};
pub use sync_backend::{
    ApplyBackend, ApplyReport, CleanBackend, CleanOpts, CleanReport, InstallBackend, InstallReport,
    PostApplyBackend, PreviewBackend, SyncBackend, SyncOpts, SyncPreview, SyncReport, SyncStep,
    UpdateBackend, UpdateOpts, UpdateReport,
};
pub use toolchain::{DevToolsManager, NoopDevTools, ToolStep};

pub fn resolve_features_dir(
    explicit: Option<PathBuf>,
    _reporter: &dyn ProgressReporter,
    chezmoi: &dyn chezmoi_client::ChezmoiClient,
    fs: &dyn FileSystem,
) -> Result<PathBuf, KaizenError> {
    if let Some(dir) = explicit {
        return Ok(dir);
    }
    if let Some(source) = chezmoi.source_path()? {
        let candidate = source
            .join(manifest::KAIZEN_DIR)
            .join(manifest::FEATURES_SUBDIR);
        if fs.is_dir(&candidate) {
            return Ok(candidate);
        }
    }
    // Monorepo dev layout: running kaizen from the repo root.
    let monorepo_candidate = PathBuf::from("dotfiles")
        .join(manifest::KAIZEN_DIR)
        .join(manifest::FEATURES_SUBDIR);
    if fs.is_dir(&monorepo_candidate) {
        return Ok(monorepo_candidate);
    }
    Err(KaizenError::FeaturesDirNotFound {
        path: PathBuf::from(manifest::KAIZEN_DIR).join(manifest::FEATURES_SUBDIR),
    })
}

pub struct KaizenEngine {
    features_dir: Option<PathBuf>,
    fs: Arc<dyn FileSystem>,
    nix_cache_path: Option<PathBuf>,
}

impl KaizenEngine {
    pub fn new(features_dir: impl Into<PathBuf>, fs: Arc<dyn FileSystem>) -> Self {
        Self {
            features_dir: Some(features_dir.into()),
            fs,
            nix_cache_path: None,
        }
    }

    /// Engine that reads exclusively from the Nix feature cache.
    /// Returns `FeaturesDirNotFound` if the cache is unavailable.
    pub fn cache_only(fs: Arc<dyn FileSystem>) -> Self {
        Self {
            features_dir: None,
            fs,
            nix_cache_path: None,
        }
    }

    pub fn with_nix_cache(mut self, path: PathBuf) -> Self {
        self.nix_cache_path = Some(path);
        self
    }

    pub fn load_config(&self, path: &Path) -> Result<UserConfig, KaizenError> {
        config::load_with(path, self.fs.as_ref())
    }

    pub fn default_config_path(paths: &dyn PathProvider) -> PathBuf {
        paths
            .config_dir()
            .unwrap_or_else(|| PathBuf::from(".config"))
            .join("kaizen")
            .join("config.toml")
    }

    fn feature_store(&self) -> Result<FeatureStore, KaizenError> {
        let dir = self
            .features_dir
            .as_deref()
            .ok_or_else(|| KaizenError::FeaturesDirNotFound {
                path: PathBuf::from(manifest::KAIZEN_DIR).join(manifest::FEATURES_SUBDIR),
            })?;
        Ok(FeatureStore::new(dir, Arc::clone(&self.fs)))
    }

    pub fn list_features(&self) -> Result<Vec<String>, KaizenError> {
        self.feature_store()?.list()
    }

    /// Returns `(name, description)` pairs.
    ///
    /// Priority:
    /// 1. `feature-meta.json` generated by home-manager activation (Nix machines).
    /// 2. Scanning `features/*.toml` — fresh machines / non-Nix fallback.
    pub fn list_features_with_meta(&self) -> Result<Vec<(String, Option<String>)>, KaizenError> {
        if let Some(ref cache_path) = self.nix_cache_path {
            if let Some(map) = nix_feature_cache::load(cache_path, self.fs.as_ref())? {
                return Ok(map
                    .into_iter()
                    .map(|(name, meta)| {
                        let desc = Some(meta.description).filter(|d| !d.is_empty());
                        (name, desc)
                    })
                    .collect());
            }
        }
        let store = self.feature_store()?;
        store
            .list()?
            .into_iter()
            .map(|name| {
                let desc = store.load_optional(&name)?.and_then(|f| f.meta.description);
                Ok((name, desc))
            })
            .collect()
    }

    pub fn build_workflow_plan(
        &self,
        config: &UserConfig,
        target_os: TargetOs,
    ) -> Result<WorkflowPlan, KaizenError> {
        // Feature names used only to scope the install plan.
        // For the Nix backend packages come from home-manager, so an empty
        // list is safe — sync still runs chezmoi + home-manager correctly.
        let all_names: Vec<String> = if let Some(ref cache_path) = self.nix_cache_path {
            if let Some(map) = nix_feature_cache::load(cache_path, self.fs.as_ref())? {
                map.into_keys().collect()
            } else {
                self.feature_store()
                    .and_then(|s| s.list())
                    .unwrap_or_default()
            }
        } else {
            self.feature_store()
                .and_then(|s| s.list())
                .unwrap_or_default()
        };
        let store = self.feature_store().unwrap_or_else(|_| {
            FeatureStore::new(
                PathBuf::from(manifest::KAIZEN_DIR).join(manifest::FEATURES_SUBDIR),
                Arc::clone(&self.fs),
            )
        });
        merge::build_plan(config, &store, &all_names, target_os)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fs::mem::MemFileSystem;

    struct SourceClient {
        source: Option<PathBuf>,
    }

    impl chezmoi_client::ChezmoiClient for SourceClient {
        fn managed_files(&self) -> Result<Vec<PathBuf>, KaizenError> {
            Ok(vec![])
        }

        fn locally_modified_files(&self) -> Result<Vec<PathBuf>, KaizenError> {
            Ok(vec![])
        }

        fn source_path(&self) -> Result<Option<PathBuf>, KaizenError> {
            Ok(self.source.clone())
        }
        fn raw_source_path(&self) -> Result<Option<PathBuf>, KaizenError> {
            Ok(self.source.clone())
        }
        fn pull_source(&self, _: &Path) -> Result<(), KaizenError> {
            Ok(())
        }
        fn current_remote(&self, _: &Path) -> Result<Option<String>, KaizenError> {
            Ok(None)
        }

        fn init_source(&self, _: &str) -> Result<(), KaizenError> {
            Ok(())
        }

        fn apply(&self, _force: bool) -> Result<(), KaizenError> {
            Ok(())
        }

        fn remove_files(
            &self,
            files: &[PathBuf],
            _: bool,
        ) -> Result<RemoveFilesReport, KaizenError> {
            Ok(RemoveFilesReport {
                removed: files.to_vec(),
                skipped: vec![],
            })
        }

        fn backup_source_dir(
            &self,
            source_dir: &Path,
        ) -> Result<chezmoi_client::SourceBackup, KaizenError> {
            Ok(chezmoi_client::SourceBackup {
                backup_path: source_dir.with_extension("bak"),
                restore_path: source_dir.to_owned(),
            })
        }
    }

    #[test]
    fn resolve_features_dir_finds_features_in_chezmoi_source() {
        let fs = MemFileSystem::new();
        let source = PathBuf::from("/source");
        let features = source
            .join(manifest::KAIZEN_DIR)
            .join(manifest::FEATURES_SUBDIR);
        fs.add_dir(&features);

        let result = resolve_features_dir(
            None,
            &NoopReporter,
            &SourceClient {
                source: Some(source),
            },
            &fs,
        )
        .unwrap();

        assert_eq!(result, features);
    }

    #[test]
    fn resolve_features_dir_errors_when_source_has_no_features() {
        let fs = MemFileSystem::new();

        let result = resolve_features_dir(
            None,
            &NoopReporter,
            &SourceClient {
                source: Some(PathBuf::from("/source")),
            },
            &fs,
        );

        assert!(matches!(
            result,
            Err(KaizenError::FeaturesDirNotFound { .. })
        ));
    }

    #[test]
    fn list_features_with_meta_reads_from_feature_store() {
        let fs = Arc::new(MemFileSystem::new());
        let features_dir = PathBuf::from("/kaizen/features");
        fs.add_dir(&features_dir);
        fs.add_file(
            features_dir.join("core.toml"),
            "[meta]\ndescription = \"core CLI tools\"",
        );
        fs.add_file(
            features_dir.join("vcs.toml"),
            "[meta]\ndescription = \"version control tooling\"",
        );
        let engine = KaizenEngine::new(features_dir, fs);
        let meta = engine.list_features_with_meta().unwrap();
        assert_eq!(
            meta,
            vec![
                ("core".to_owned(), Some("core CLI tools".to_owned())),
                ("vcs".to_owned(), Some("version control tooling".to_owned())),
            ]
        );
    }

    #[test]
    fn cache_only_build_workflow_plan_without_cache_returns_empty_plan() {
        let fs = Arc::new(MemFileSystem::new());
        let engine = KaizenEngine::cache_only(fs);
        let config: UserConfig = toml::from_str("").unwrap();
        let plan = engine
            .build_workflow_plan(&config, TargetOs::Linux)
            .unwrap();
        assert!(plan.install_plan.programs.is_empty());
    }

    #[test]
    fn cache_only_build_workflow_plan_with_valid_cache_returns_empty_plan() {
        let fs = Arc::new(MemFileSystem::new());
        let cache = PathBuf::from("/cache/feature-meta.json");
        fs.add_file(
            &cache,
            r#"{"core":{"description":"Core","category":"system"}}""}"#.trim_end_matches("\"\"}"),
        );
        // cache loads, plan builds without programs (no feature toml files)
        let engine = KaizenEngine::cache_only(fs).with_nix_cache(cache);
        let config: UserConfig = toml::from_str("").unwrap();
        let plan = engine
            .build_workflow_plan(&config, TargetOs::Linux)
            .unwrap();
        assert!(plan.install_plan.programs.is_empty());
    }

    #[test]
    fn resolve_features_dir_uses_monorepo_layout_when_no_chezmoi_source() {
        let fs = MemFileSystem::new();
        let monorepo_features = PathBuf::from("dotfiles")
            .join(manifest::KAIZEN_DIR)
            .join(manifest::FEATURES_SUBDIR);
        fs.add_dir(&monorepo_features);

        let result =
            resolve_features_dir(None, &NoopReporter, &SourceClient { source: None }, &fs).unwrap();

        assert_eq!(result, monorepo_features);
    }
}
