use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::{FileSystem, KaizenError};

#[derive(Debug, Clone, Deserialize, Serialize, Default, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum OnFailure {
    #[default]
    Warn,
    Fail,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UpdateHook {
    /// Command + arguments, e.g. `["pi", "update", "--extensions"]`.
    pub run: Vec<String>,
    #[serde(default, rename = "onFailure")]
    pub on_failure: OnFailure,
}

#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct BumpWorkflow {
    #[serde(default)]
    pub before: Vec<UpdateHook>,
    #[serde(default)]
    pub run: Vec<UpdateHook>,
    #[serde(default)]
    pub capture: Vec<String>,
}

impl BumpWorkflow {
    pub fn is_empty(&self) -> bool {
        self.before.is_empty() && self.run.is_empty() && self.capture.is_empty()
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct NixFeatureMeta {
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub category: String,
    /// Legacy field — kept for backward compat
    #[serde(default, rename = "updateHooks")]
    pub update_hooks: Vec<UpdateHook>,
    /// New field: kaizen update hooks
    #[serde(default)]
    pub update: Vec<UpdateHook>,
    /// New field: bump workflow
    #[serde(default)]
    pub bump: BumpWorkflow,
}

/// Load `feature-meta.json` generated by the home-manager activation script.
///
/// Returns `None` when the file does not exist yet (fresh machine before
/// first `home-manager switch`).  In that case the caller falls back to
/// scanning `kaizen/features/*.toml` via `FeatureStore`.
pub fn load(
    path: &Path,
    fs: &dyn FileSystem,
) -> Result<Option<BTreeMap<String, NixFeatureMeta>>, KaizenError> {
    if !fs.exists(path) {
        return Ok(None);
    }
    let raw = fs.read_to_string(path)?;
    let map = serde_json::from_str::<BTreeMap<String, NixFeatureMeta>>(&raw)
        .map_err(|e| KaizenError::FeatureCacheParse(e.to_string()))?;
    Ok(Some(map))
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::fs::mem::MemFileSystem;

    fn mem_fs_with(path: &str, content: &str) -> MemFileSystem {
        let fs = MemFileSystem::new();
        fs.add_file(PathBuf::from(path), content.as_bytes());
        fs
    }

    #[test]
    fn returns_none_when_file_missing() {
        let fs = MemFileSystem::new();
        let result = load(Path::new("/missing.json"), &fs).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn parses_feature_meta_json() {
        let json = r#"{"helix":{"description":"Helix editor","category":"editor"},"vcs":{"description":"VCS tools","category":"vcs"}}"#;
        let fs = mem_fs_with("/feature-meta.json", json);
        let map = load(Path::new("/feature-meta.json"), &fs).unwrap().unwrap();
        assert_eq!(map["helix"].description, "Helix editor");
        assert_eq!(map["helix"].category, "editor");
        assert_eq!(map.len(), 2);
    }

    #[test]
    fn tolerates_missing_fields_with_defaults() {
        let fs = mem_fs_with("/feature-meta.json", r#"{"core":{}}"#);
        let map = load(Path::new("/feature-meta.json"), &fs).unwrap().unwrap();
        assert_eq!(map["core"].description, "");
        assert_eq!(map["core"].category, "");
    }

    #[test]
    fn returns_error_on_invalid_json() {
        let fs = mem_fs_with("/feature-meta.json", "not json");
        assert!(matches!(
            load(Path::new("/feature-meta.json"), &fs),
            Err(KaizenError::FeatureCacheParse(_))
        ));
    }

    #[test]
    fn parses_bump_workflow() {
        let json = r#"{
            "mise": {
                "description": "Mise toolchains",
                "category": "dev",
                "bump": {
                    "before": [{"run": ["mise", "install"], "onFailure": "fail"}],
                    "run": [{"run": ["mise-bump"], "onFailure": "fail"}],
                    "capture": ["/tmp/mise.lock"]
                }
            }
        }"#;
        let fs = mem_fs_with("/feature-meta.json", json);
        let map = load(Path::new("/feature-meta.json"), &fs).unwrap().unwrap();
        let bump = &map["mise"].bump;
        assert_eq!(bump.before.len(), 1);
        assert_eq!(bump.before[0].run, vec!["mise", "install"]);
        assert_eq!(bump.run.len(), 1);
        assert_eq!(bump.capture, vec!["/tmp/mise.lock"]);
    }

    #[test]
    fn bump_workflow_is_empty_when_absent() {
        let fs = mem_fs_with("/feature-meta.json", r#"{"core":{}}"#);
        let map = load(Path::new("/feature-meta.json"), &fs).unwrap().unwrap();
        assert!(map["core"].bump.is_empty());
    }

    #[test]
    fn seed_file_contains_bump_workflows_for_mise_and_nix_system() {
        let seed_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../dotfiles/dot_config/kaizen/feature-meta.json");
        let content = std::fs::read_to_string(&seed_path)
            .expect("seed file must exist at dotfiles/dot_config/kaizen/feature-meta.json");
        let map: std::collections::BTreeMap<String, NixFeatureMeta> =
            serde_json::from_str(&content).expect("seed file must be valid JSON");

        let mise = map.get("mise").expect("seed must have 'mise' entry");
        assert!(
            !mise.bump.run.is_empty() || !mise.bump.capture.is_empty(),
            "mise bump must have run or capture"
        );

        let nix = map
            .get("nix-system")
            .expect("seed must have 'nix-system' entry");
        assert!(
            !nix.bump.run.is_empty() || !nix.bump.capture.is_empty(),
            "nix-system bump must have run or capture"
        );
    }
}
