use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::{FileSystem, KaizenError};

#[derive(Debug, Clone, Deserialize, Serialize, Default, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum OnFailure {
    #[default]
    Warn,
    Fail,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UpdateHook {
    /// Command + arguments, e.g. `["pi", "update", "--extensions"]`.
    pub run: Vec<String>,
    #[serde(default, rename = "onFailure")]
    pub on_failure: OnFailure,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NixFeatureMeta {
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub category: String,
    #[serde(default, rename = "updateHooks")]
    pub update_hooks: Vec<UpdateHook>,
}

/// Load `feature-meta.json` generated by the home-manager activation script.
///
/// Returns `None` when the file does not exist yet (fresh machine before
/// first `home-manager switch`).  In that case the caller falls back to
/// scanning `kaizen/features/*.toml` via `FeatureStore`.
pub fn load(
    path: &Path,
    fs: &dyn FileSystem,
) -> Result<Option<BTreeMap<String, NixFeatureMeta>>, KaizenError> {
    if !fs.exists(path) {
        return Ok(None);
    }
    let raw = fs.read_to_string(path)?;
    let map = serde_json::from_str::<BTreeMap<String, NixFeatureMeta>>(&raw)
        .map_err(|e| KaizenError::FeatureCacheParse(e.to_string()))?;
    Ok(Some(map))
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::fs::mem::MemFileSystem;

    fn mem_fs_with(path: &str, content: &str) -> MemFileSystem {
        let fs = MemFileSystem::new();
        fs.add_file(PathBuf::from(path), content.as_bytes());
        fs
    }

    #[test]
    fn returns_none_when_file_missing() {
        let fs = MemFileSystem::new();
        let result = load(Path::new("/missing.json"), &fs).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn parses_feature_meta_json() {
        let json = r#"{"helix":{"description":"Helix editor","category":"editor"},"vcs":{"description":"VCS tools","category":"vcs"}}"#;
        let fs = mem_fs_with("/feature-meta.json", json);
        let map = load(Path::new("/feature-meta.json"), &fs).unwrap().unwrap();
        assert_eq!(map["helix"].description, "Helix editor");
        assert_eq!(map["helix"].category, "editor");
        assert_eq!(map.len(), 2);
    }

    #[test]
    fn tolerates_missing_fields_with_defaults() {
        let fs = mem_fs_with("/feature-meta.json", r#"{"core":{}}"#);
        let map = load(Path::new("/feature-meta.json"), &fs).unwrap().unwrap();
        assert_eq!(map["core"].description, "");
        assert_eq!(map["core"].category, "");
    }

    #[test]
    fn returns_error_on_invalid_json() {
        let fs = mem_fs_with("/feature-meta.json", "not json");
        assert!(matches!(
            load(Path::new("/feature-meta.json"), &fs),
            Err(KaizenError::FeatureCacheParse(_))
        ));
    }
}
