;;; semel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from scope.el

(autoload 'scope-define-symbol-type "scope"
"

(fn NAME PARENTS &rest PROPS)" nil t)
(autoload 'scope-get-symbol-type-property "scope"
"

(fn TYPE PROP)")
(autoload 'scope-symbol-type-p "scope"
"

(fn SYM)")
(autoload 'scope-describe-symbol-type "scope"
"

(fn TYPE)" t)
(autoload 'scope "scope"
"Read and analyze code from STREAM, reporting findings via CALLBACK.

Call CALLBACK for each analyzed symbol SYM with arguments TYPE, POS,
LEN, ID and DEF, where TYPE is a symbol that specifies the semantics of
SYM; POS is the position of SYM in STREAM; LEN is SYM's length; ID is an
object that uniquely identifies (co-)occurrences of SYM in the current
defun; and DEF is the position in which SYM is locally defined, or nil.
If SYM is itself a binding occurrence, then POS and BINDER are equal.
If SYM is not lexically bound, then BINDER is nil.  This function
ignores `read-symbol-shorthands', so SYM and LEN always correspond to
the symbol as it appears in STREAM.

If STREAM is nil, it defaults to the current buffer.

This function recursively analyzes Lisp forms (HEAD . TAIL), usually
starting with a top-level form, by inspecting HEAD at each level.

(fn CALLBACK &optional STREAM)")
(register-definition-prefixes "scope" '("scope-"))


;;; Generated autoloads from semel.el

(autoload 'semel-mode "semel"
"Semantic highlighting for Emacs Lisp.

This is a minor mode.  If called interactively, toggle the `Semel mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `semel-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" '(emacs-lisp-mode))
(register-definition-prefixes "semel" '("semel-"))

;;; End of scraped data

(provide 'semel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; semel-autoloads.el ends here
