(declare-module "skhd"
  :os          '(darwin)
  :group       'keyboard-daemon
  :description "Hotkey daemon — canonical global-shortcut provider")

(brew! "koekeishiya/formulae/skhd")

(define *rules* '())

(define (collect-rule! action key cmd)
  (set! *rules* (cons (list action key cmd) *rules*)))

; Canonical hook: any module that wants global shortcuts uses this name,
; regardless of whether skhd or another daemon is underneath.
(provide-hook "global-shortcut" collect-rule!)

(on-apply!
  (lambda ()
    (generate-file! "~/.config/skhd/skhdrc"
      (string-append "# generated by kaizen\n# rules: "
                     (number->string (length *rules*))))))
