;;; persistent-values-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from persistent-values.el

(autoload 'persistent-values-add "persistent-values"
"Add VALUE to `persistent-values--data' and save to disk.
If VALUE is not explicitly given, use the word at point or the selected region.

(fn VALUE)" t)
(autoload 'persistent-values-remove "persistent-values"
"Remove VALUE from `persistent-values--data' and save to disk.
VALUE is selected via completion.

(fn VALUE)" t)
(autoload 'persistent-values-search "persistent-values"
"Search for a value in `persistent-values--data' via completion and insert it at point." t)
(defvar persistent-values-mode nil
"Non-nil if Persistent-Values mode is enabled.
See the `persistent-values-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `persistent-values-mode'.")
(custom-autoload 'persistent-values-mode "persistent-values" nil)
(autoload 'persistent-values-mode "persistent-values"
"Minor mode for persistently storing text and searching it via completion.

When enabled, data is automatically loaded from `persistent-values-file'.

This is a global minor mode.  If called interactively, toggle the
`Persistent-Values mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='persistent-values-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "persistent-values" '("persistent-values-"))

;;; End of scraped data

(provide 'persistent-values-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; persistent-values-autoloads.el ends here
