;;; kdl-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from kdl-mode.el

(autoload 'kdl-mode "kdl-mode"
"Major mode for editing KDL document language.

In addition to any hooks its parent mode `prog-mode' might have run,
this mode runs the hook `kdl-mode-hook', as the final or penultimate
step during initialization.

\\{kdl-mode-map}" t)
(add-to-list 'auto-mode-alist '("\\.kdl\\'" . kdl-mode))
(register-definition-prefixes "kdl-mode" '("kdl-"))

;;; End of scraped data

(provide 'kdl-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kdl-mode-autoloads.el ends here
