#!/usr/bin/env python3
"""
ai-workers-setup <scope> [cwd]

Idempotently ensures three pi-link agents are running for the given scope:
  <scope>@coder
  <scope>@researcher
  <scope>@critic

Layout: 2x2 tiled grid in the ai-workers tab.
  ┌────────────┬────────────┐
  │   critic   │   coder    │
  ├────────────┼────────────┤
  │ researcher │   (shell)  │
  └────────────┴────────────┘

Pane IDs are persisted per workspace in ~/.config/herdr/ai-workers-layout.json
so the same panes are always reused — no orphaned panes accumulate.
Models are read from ~/.config/kaizen/models.toml (generated by chezmoi).
"""
import json
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Optional

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore

from .registry import detect

ROLES = ["critic", "coder", "researcher"]
TAB_LABEL = "ai-workers"
STATE_FILE = Path.home() / ".config" / "herdr" / "ai-workers-layout.json"
MODELS_FILE = Path.home() / ".config" / "kaizen" / "models.toml"
ROLE_MODEL_KEY = {"coder": "coder", "researcher": "research", "critic": "reviewer"}
AGENT_START_TIMEOUT_MS = 120_000
LIVE_STATUSES = {"idle", "working", "blocked"}


def eprint(msg: str) -> None:
    print(msg, file=sys.stderr)


def load_models() -> dict[str, str]:
    if MODELS_FILE.exists():
        return tomllib.loads(MODELS_FILE.read_text()).get("models", {})
    return {}


def model_for_role(role: str) -> Optional[str]:
    key = ROLE_MODEL_KEY.get(role)
    return load_models().get(key) if key else None


def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


def save_state(state: dict) -> None:
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2))


def setup(scope: str, cwd: str) -> None:
    adapter = detect()
    eprint(f"[ai-workers] multiplexer: {type(adapter).__name__}")

    workspace_id = adapter.current_workspace_id(cwd)
    if not workspace_id:
        raise RuntimeError(f"No workspace found matching cwd: {cwd}")
    eprint(f"[ai-workers] workspace: {workspace_id}")

    panes = _ensure_panes(adapter, workspace_id, cwd)

    missing = {
        role: pane_id
        for role, pane_id in panes.items()
        if adapter.get_pane_agent_status(pane_id) not in LIVE_STATUSES
    }

    if not missing:
        eprint("[ai-workers] all agents already running — nothing to do")
        return

    eprint(f"[ai-workers] starting: {', '.join(f'{scope}@{r}' for r in missing)}")
    _start_agents(adapter, missing, scope)


def _ensure_panes(adapter, workspace_id: str, cwd: str) -> dict[str, str]:
    """Return {role: pane_id} for critic/coder/researcher, creating if needed."""
    state = load_state()
    stored = state.get(workspace_id, {})

    if stored:
        alive = {role: pid for role, pid in stored.items() if adapter.pane_alive(pid)}
        if set(alive) == set(ROLES):
            eprint("[ai-workers] reusing stored panes")
            return alive
        eprint("[ai-workers] stored panes stale, rebuilding layout")

    tab_id, anchor_pane_id = _ensure_tab(adapter, workspace_id, cwd)
    panes = _build_tiled_layout(adapter, anchor_pane_id)

    state[workspace_id] = panes
    save_state(state)
    return panes


def _ensure_tab(adapter, workspace_id: str, cwd: str) -> tuple[str, str]:
    """Return (tab_id, anchor_pane_id). Creates tab if missing."""
    tabs = adapter.list_tabs(workspace_id)
    existing = next((t for t in tabs if t.label == TAB_LABEL), None)

    if existing:
        eprint(f"[ai-workers] tab exists: {existing.tab_id}")
        panes = adapter.list_panes_in_tab(existing.tab_id)
        if not panes:
            raise RuntimeError(f"Tab {existing.tab_id} has no panes")
        return existing.tab_id, panes[0].pane_id

    eprint(f"[ai-workers] creating tab '{TAB_LABEL}'")
    tab, root_pane = adapter.create_tab(workspace_id, TAB_LABEL, cwd)
    return tab.tab_id, root_pane.pane_id


def _build_tiled_layout(adapter, anchor_pane_id: str) -> dict[str, str]:
    """Build 2x2 grid from anchor pane. Returns {role: pane_id}.

    Split sequence:
      anchor ──right──▶ coder
      anchor ──down───▶ researcher
      coder  ──down───▶ (shell / 4th pane)

    Result:
      ┌────────────┬────────────┐
      │   critic   │   coder    │
      │  (anchor)  │  (right)   │
      ├────────────┼────────────┤
      │ researcher │   (shell)  │
      │  (down)    │  (right↓)  │
      └────────────┴────────────┘
    """
    eprint("[ai-workers] building 2x2 tiled layout")

    coder_pane = adapter.split_pane(anchor_pane_id, "right")
    researcher_pane = adapter.split_pane(anchor_pane_id, "down")
    adapter.split_pane(coder_pane.pane_id, "down")

    adapter.rename_pane(anchor_pane_id, "critic")
    adapter.rename_pane(coder_pane.pane_id, "coder")
    adapter.rename_pane(researcher_pane.pane_id, "researcher")

    return {
        "critic": anchor_pane_id,
        "coder": coder_pane.pane_id,
        "researcher": researcher_pane.pane_id,
    }


def _start_agents(adapter, missing: dict[str, str], scope: str) -> None:
    """Run pi-link in each dead pane, wait for all in parallel."""
    for role, pane_id in missing.items():
        name = f"{scope}@{role}"
        model = model_for_role(role)
        cmd = f"pi-link {name}"
        if model:
            cmd += f" --model {model}"
        eprint(f"[ai-workers] {name} → pane {pane_id} (model: {model or 'default'})")
        adapter.run_in_pane(pane_id, cmd)

    def wait_one(role: str, pane_id: str) -> str:
        if not adapter.wait_pane_idle(pane_id, timeout_ms=AGENT_START_TIMEOUT_MS):
            raise RuntimeError(f"Timeout waiting for {scope}@{role}")
        return f"{scope}@{role}"

    with ThreadPoolExecutor() as pool:
        futures = {pool.submit(wait_one, role, pane_id): role for role, pane_id in missing.items()}
        for future in as_completed(futures):
            eprint(f"[ai-workers] {future.result()} ready")


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    scope = sys.argv[1]
    cwd = sys.argv[2] if len(sys.argv) > 2 else str(Path.cwd())

    try:
        setup(scope, cwd)
    except RuntimeError as e:
        eprint(f"[ai-workers] error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
