;;; mermaid-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from mermaid-ts-mode.el

(autoload 'mermaid-ts-mode "mermaid-ts-mode"
"Major mode derived from `prog-mode' by `define-derived-mode'.
It inherits all of the parent's attributes, but has its own keymap,
abbrev table and syntax table:

  `mermaid-ts-mode-map', `mermaid-ts-mode-abbrev-table' and
`mermaid-ts--syntax-table'

which more-or-less shadow prog-mode's corresponding tables.

In addition to any hooks its parent mode might have run, this mode
runs the hook `mermaid-ts-mode-hook', as the final or penultimate step
during initialization.

\\{mermaid-ts-mode-map}" t)
(register-definition-prefixes "mermaid-ts-mode" '("mermaid-ts-"))

;;; End of scraped data

(provide 'mermaid-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mermaid-ts-mode-autoloads.el ends here
