[tools]
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "latest"
"npm:@github/copilot-language-server" = "1.531.0"
"cargo:kdlfmt" = "latest"
"cargo:codebook-lsp" = "latest"
"npm:lua-fmt" = "2.6.0"
