use std::{collections::BTreeMap, path::PathBuf};

/// Extract the key-string list from either a plain array `["k1","k2"]`
/// or an object `{ keys = ["k1","k2"], ... }` shortcut value.
fn extract_keys(value: &toml::Value) -> Option<Vec<String>> {
    match value {
        toml::Value::Array(arr) => arr.iter().map(|v| v.as_str().map(String::from)).collect(),
        toml::Value::Table(t) => t
            .get("keys")?
            .as_array()?
            .iter()
            .map(|v| v.as_str().map(String::from))
            .collect(),
        _ => None,
    }
}

use crate::{
    chezmoi::merge_kaizen_data_with,
    chezmoi_client::ChezmoiClient,
    container::ContainerCleaner,
    executor::{ProcessCommand, ProcessExecutor},
    fs::FileSystem,
    paths::PathProvider,
    progress::ProgressReporter,
    sync_backend::{ApplyReport, CleanReport},
    variants::{discover_variants, VariantResolver},
    ConfigPlan, KaizenError, PackageManagerKind, TargetOs,
};

pub fn chezmoi_write_and_apply(
    plan: &ConfigPlan,
    dry_run: bool,
    force: bool,
    reporter: &dyn ProgressReporter,
    client: &dyn ChezmoiClient,
    fs: &dyn FileSystem,
    paths: &dyn PathProvider,
) -> Result<ApplyReport, KaizenError> {
    if dry_run {
        return Ok(ApplyReport { data_path: None });
    }

    // Ensure chezmoi source is initialized (clone dotfiles repo if needed).
    if client.source_path()?.is_none() {
        let url = plan
            .dotfiles_source
            .as_deref()
            .ok_or(KaizenError::ChezmoidataTargetUnknown)?;
        client.init_source(url)?;
    }

    // Pull latest dotfiles from remote before applying — but only when the
    // chezmoi source is a real clone, not a developer symlink.  When it is a
    // symlink the developer manages their own VCS and a silent pull would
    // overwrite uncommitted work.
    if let Some(source) = client.source_path()? {
        // The adapter decides whether to pull (symlink, git root detection,
        // offline tolerance). Non-fatal: diverge / no-remote is fine.
        let _ = client.pull_source(&source);
    }

    // Write features data to ~/.config/kaizen/data.toml.
    // chezmoi templates read it via `include | fromToml`.
    // Nix feature-meta.json is generated by the home-manager activation script.
    let data_path = write_kaizen_data(plan, paths, fs)?;
    write_variant_data_to_chezmoi(plan, &data_path, client, fs, &TargetOs::detect())?;
    export_shortcuts_to_chezmoi(
        client,
        fs,
        &TargetOs::detect(),
        plan.settings.layout.as_deref(),
    )?;

    reporter.step("→ chezmoi apply");
    client.apply(force)?;

    Ok(ApplyReport {
        data_path: Some(data_path),
    })
}

/// Write features data to `~/.config/kaizen/data.toml` — the single source of truth.
///
/// Merges with any existing content so unknown keys (e.g. user-added data) are preserved.
fn write_kaizen_data(
    plan: &ConfigPlan,
    paths: &dyn PathProvider,
    fs: &dyn FileSystem,
) -> Result<PathBuf, KaizenError> {
    let config_dir = paths.config_dir().ok_or(KaizenError::HomeDirUnavailable)?;
    let kaizen_dir = config_dir.join("kaizen");
    let data_path = kaizen_dir.join("data.toml");
    fs.create_dir_all(&kaizen_dir)?;
    let content = merge_kaizen_data_with(&data_path, plan, fs)?;
    fs.write(&data_path, content.as_bytes())?;
    Ok(data_path)
}

/// Synchronise all known slot selections into `.chezmoidata.toml` as nested
/// TOML tables.  For `tiling.wm = "aerospace"` this writes:
/// ```toml
/// [tiling]
/// wm = "aerospace"
/// ```
/// Keys owned by kaizen are brought up-to-date (or deleted if the slot has no
/// effective variant).  User-managed keys are left untouched.
fn write_variant_data_to_chezmoi(
    plan: &ConfigPlan,
    kaizen_data_path: &std::path::Path,
    client: &dyn crate::chezmoi_client::ChezmoiClient,
    fs: &dyn FileSystem,
    os: &TargetOs,
) -> Result<(), KaizenError> {
    let Some(source) = client.source_path()? else {
        return Ok(());
    };
    let chezmoidata_path = source.join(".chezmoidata.toml");

    // Read variant selections from data.toml (written by the wizard or `kaizen variant set`),
    // not from plan.variants which comes from config.toml and is always empty after a
    // plain `kaizen sync`.
    let current_selections: BTreeMap<String, String> = if fs.exists(kaizen_data_path) {
        let raw = fs.read_to_string(kaizen_data_path)?;
        toml::from_str::<toml::Value>(&raw)
            .ok()
            .and_then(|v| v.get("variants").and_then(|t| t.as_table()).cloned())
            .map(|t| {
                t.into_iter()
                    .filter_map(|(k, v)| Some((k, v.as_str()?.to_owned())))
                    .collect()
            })
            .unwrap_or_default()
    } else {
        plan.variants.clone()
    };

    // Build resolver from the repo's features directory (parent of dotfiles source).
    let repo_root = source.parent().unwrap_or(&source);
    let features_dir = repo_root.join("features");
    let resolver = if fs.exists(&features_dir) {
        let variants = discover_variants(&features_dir, fs)?;
        Some(VariantResolver::new(variants))
    } else {
        None
    };

    // Only touch the file when there is something to write or a resolver that
    // can tell us what to delete.
    if resolver.is_none() && current_selections.is_empty() {
        return Ok(());
    }

    let mut table: toml::map::Map<String, toml::Value> = if fs.exists(&chezmoidata_path) {
        let raw = fs.read_to_string(&chezmoidata_path)?;
        match toml::from_str::<toml::Value>(&raw) {
            Ok(toml::Value::Table(t)) => t,
            _ => toml::map::Map::new(),
        }
    } else {
        toml::map::Map::new()
    };

    let slots: Vec<String> = match &resolver {
        Some(r) => r.list_slots(),
        None => current_selections.keys().cloned().collect(),
    };

    for slot in &slots {
        let effective_id = match &resolver {
            Some(r) => r
                .effective(slot, os, &current_selections)
                .map(|v| v.id.as_str()),
            None => current_selections.get(slot.as_str()).map(|s| s.as_str()),
        };
        set_slot_in_chezmoidata(&mut table, slot, effective_id);
    }

    let content =
        toml::to_string_pretty(&toml::Value::Table(table)).map_err(KaizenError::TomlSerialize)?;
    fs.write(&chezmoidata_path, content.as_bytes())?;
    Ok(())
}

/// Write or delete a slot entry in a chezmoidata TOML table.
///
/// `tiling.wm` with `Some("aerospace")` → creates/updates `[tiling] wm = "aerospace"`.
/// `tiling.wm` with `None` → removes `wm` key from `[tiling]`; removes `[tiling]` if empty.
fn set_slot_in_chezmoidata(
    table: &mut toml::map::Map<String, toml::Value>,
    slot: &str,
    value: Option<&str>,
) {
    let mut parts = slot.splitn(2, '.');
    match (parts.next(), parts.next()) {
        (Some(section), Some(key)) => match value {
            Some(id) => {
                let section_val = table
                    .entry(section.to_owned())
                    .or_insert_with(|| toml::Value::Table(Default::default()));
                if let toml::Value::Table(t) = section_val {
                    t.insert(key.to_owned(), toml::Value::String(id.to_owned()));
                }
            }
            None => {
                if let Some(toml::Value::Table(t)) = table.get_mut(section) {
                    t.remove(key);
                    if t.is_empty() {
                        table.remove(section);
                    }
                }
            }
        },
        (Some(key), None) => match value {
            Some(id) => {
                table.insert(key.to_owned(), toml::Value::String(id.to_owned()));
            }
            None => {
                table.remove(key);
            }
        },
        _ => {}
    }
}

/// Export the unified shortcut catalog into `.chezmoidata.toml` under `[kaizen.shortcuts]`.
///
/// Reads `kaizen/keybindings.toml` (falls back to `kaizen/mnemonics.toml` for backward
/// compatibility).  Applies shortcuts in two layers:
///
/// 1. `[shortcuts]` — base (qwerty-compatible) definitions.
/// 2. `[layout.<layout>.shortcuts]` — overlay merged on top of base when `layout` is set.
///    Overlay keys replace base keys; keys not in the overlay are taken from base.
///
/// After merging, all token values are subject to platform-modifier resolution:
/// tokens matching a key in `[modifiers.<os>]` are replaced with their platform-native
/// value (e.g. `CTRL` → `"Ctrl"`).  All other tokens pass through unchanged.
///
/// No-op when neither `keybindings.toml` nor `mnemonics.toml` is present.  Returns
/// `KaizenError::ConfigParse` when the file or an existing `.chezmoidata.toml` is
/// invalid TOML.  Preserves all unrelated `.chezmoidata.toml` keys.
fn export_shortcuts_to_chezmoi(
    client: &dyn crate::chezmoi_client::ChezmoiClient,
    fs: &dyn FileSystem,
    os: &TargetOs,
    layout: Option<&str>,
) -> Result<(), KaizenError> {
    let Some(source) = client.source_path()? else {
        return Ok(());
    };

    let primary = source
        .join(crate::manifest::KAIZEN_DIR)
        .join("keybindings.toml");
    let catalog_path = if fs.exists(&primary) {
        primary
    } else {
        let legacy = source
            .join(crate::manifest::KAIZEN_DIR)
            .join("mnemonics.toml");
        if !fs.exists(&legacy) {
            return Ok(());
        }
        legacy
    };

    let raw = fs.read_to_string(&catalog_path)?;
    let val: toml::Value = toml::from_str(&raw).map_err(|e| KaizenError::ConfigParse {
        path: catalog_path.clone(),
        source: e,
    })?;

    let platform_key = match os {
        TargetOs::Darwin => "darwin",
        _ => "linux",
    };

    let modifiers = val
        .get("modifiers")
        .and_then(|m| m.get(platform_key))
        .and_then(|t| t.as_table())
        .cloned()
        .unwrap_or_default();

    // Build merged shortcuts: base + layout overlay.
    let mut shortcuts_table = match val.get("shortcuts").and_then(|s| s.as_table()) {
        Some(t) => t.clone(),
        None => return Ok(()),
    };
    if let Some(l) = layout {
        if let Some(overlay) = val
            .get("layout")
            .and_then(|ls| ls.get(l))
            .and_then(|lv| lv.get("shortcuts"))
            .and_then(|s| s.as_table())
        {
            for (k, v) in overlay {
                shortcuts_table.insert(k.clone(), v.clone());
            }
        }
    }

    let mut resolved: toml::map::Map<String, toml::Value> = toml::map::Map::new();
    for (id, tokens_val) in &shortcuts_table {
        if let Some(key_strings) = extract_keys(tokens_val) {
            let resolved_arr: Vec<toml::Value> = key_strings
                .iter()
                .map(|s| {
                    let native = modifiers
                        .get(s.as_str())
                        .and_then(|v| v.as_str())
                        .unwrap_or(s);
                    toml::Value::String(native.to_owned())
                })
                .collect();
            resolved.insert(id.clone(), toml::Value::Array(resolved_arr));
        }
    }

    let chezmoidata_path = source.join(".chezmoidata.toml");
    let mut table: toml::map::Map<String, toml::Value> = if fs.exists(&chezmoidata_path) {
        let existing = fs.read_to_string(&chezmoidata_path)?;
        match toml::from_str::<toml::Value>(&existing) {
            Ok(toml::Value::Table(t)) => t,
            Ok(_) => toml::map::Map::new(),
            Err(e) => {
                return Err(KaizenError::ConfigParse {
                    path: chezmoidata_path.clone(),
                    source: e,
                })
            }
        }
    } else {
        toml::map::Map::new()
    };

    let kaizen = table
        .entry("kaizen".to_owned())
        .or_insert_with(|| toml::Value::Table(Default::default()));
    if let toml::Value::Table(kaizen_tbl) = kaizen {
        kaizen_tbl.insert("shortcuts".to_owned(), toml::Value::Table(resolved));
    }

    let content =
        toml::to_string_pretty(&toml::Value::Table(table)).map_err(KaizenError::TomlSerialize)?;
    fs.write(&chezmoidata_path, content.as_bytes())?;
    Ok(())
}

pub fn os_cache_clean(
    pm: &PackageManagerKind,
    dry_run: bool,
    executor: &dyn ProcessExecutor,
    paths: &dyn PathProvider,
) -> Result<(), KaizenError> {
    let (bin, args): (&str, &[&str]) = match pm {
        PackageManagerKind::Brew => ("brew", &["cleanup"]),
        PackageManagerKind::Dnf => ("dnf", &["clean", "all"]),
        PackageManagerKind::Apt => ("apt-get", &["clean"]),
        PackageManagerKind::Pacman => ("paccache", &["-r"]),
        PackageManagerKind::Unknown => return Ok(()),
    };
    run_if_available(bin, args, dry_run, executor, paths)
}

pub fn clean_report_from_steps(steps: Vec<String>) -> CleanReport {
    CleanReport {
        freed_bytes: None,
        steps,
    }
}

pub fn clean_steps(
    pm: &PackageManagerKind,
    include_nix: bool,
    container: &dyn ContainerCleaner,
) -> Vec<String> {
    let mut steps = vec![];
    if include_nix {
        steps.push("nix-collect-garbage --delete-older-than 7d".into());
        steps.push("nix-store --optimise".into());
    }
    let pm_cmd = match pm {
        PackageManagerKind::Brew => Some("brew cleanup"),
        PackageManagerKind::Dnf => Some("dnf clean all"),
        PackageManagerKind::Apt => Some("apt-get clean"),
        PackageManagerKind::Pacman => Some("paccache -r"),
        PackageManagerKind::Unknown => None,
    };
    if let Some(cmd) = pm_cmd {
        steps.push(cmd.into());
    }
    if let Some(step) = container.clean_step() {
        steps.push(step);
    }
    steps
}

/// Run `bin args` if the binary is on PATH, skipping when `dry_run`.
fn run_if_available(
    bin: &str,
    args: &[&str],
    dry_run: bool,
    executor: &dyn ProcessExecutor,
    paths: &dyn PathProvider,
) -> Result<(), KaizenError> {
    if dry_run || !paths.is_tool_available(bin) {
        return Ok(());
    }
    executor.execute(ProcessCommand::run(bin, args.iter().copied()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_table() -> toml::map::Map<String, toml::Value> {
        toml::map::Map::new()
    }

    #[test]
    fn set_slot_writes_nested_table() {
        let mut t = empty_table();
        set_slot_in_chezmoidata(&mut t, "tiling.wm", Some("aerospace"));
        let section = t.get("tiling").and_then(|v| v.as_table()).unwrap();
        assert_eq!(
            section.get("wm").and_then(|v| v.as_str()),
            Some("aerospace")
        );
    }

    #[test]
    fn set_slot_removes_key_on_none() {
        let mut t = empty_table();
        set_slot_in_chezmoidata(&mut t, "tiling.wm", Some("yabai"));
        set_slot_in_chezmoidata(&mut t, "tiling.wm", None);
        assert!(t.get("tiling").is_none(), "empty section should be removed");
    }

    #[test]
    fn set_slot_preserves_unrelated_keys() {
        let mut t = empty_table();
        t.insert(
            "username".to_owned(),
            toml::Value::String("alice".to_owned()),
        );
        set_slot_in_chezmoidata(&mut t, "tiling.wm", Some("aerospace"));
        assert_eq!(t.get("username").and_then(|v| v.as_str()), Some("alice"));
    }

    #[test]
    fn set_slot_single_segment_writes_flat_key() {
        let mut t = empty_table();
        set_slot_in_chezmoidata(&mut t, "layout", Some("colemak"));
        assert_eq!(t.get("layout").and_then(|v| v.as_str()), Some("colemak"));
    }

    /// Regression test: `plan.variants` is empty during `kaizen sync` (it comes from
    /// `config.toml`, not `data.toml`). Variant selections must be read from
    /// `data.toml` so that a previous `kaizen variant set` or wizard choice is
    /// preserved after sync.
    #[test]
    fn write_variant_data_reads_from_data_toml_not_plan() {
        use crate::{chezmoi_client::ChezmoiClient, fs::mem::MemFileSystem, plan::ConfigPlan};
        use indexmap::IndexMap;
        use std::{path::Path, sync::Arc};

        struct SourceStub(std::path::PathBuf);
        impl ChezmoiClient for SourceStub {
            fn managed_files(&self) -> Result<Vec<std::path::PathBuf>, KaizenError> {
                Ok(vec![])
            }
            fn locally_modified_files(&self) -> Result<Vec<std::path::PathBuf>, KaizenError> {
                Ok(vec![])
            }
            fn source_path(&self) -> Result<Option<std::path::PathBuf>, KaizenError> {
                Ok(Some(self.0.clone()))
            }
            fn raw_source_path(&self) -> Result<Option<std::path::PathBuf>, KaizenError> {
                Ok(Some(self.0.clone()))
            }
            fn resolve_source_root(&self, e: &Path) -> std::path::PathBuf {
                e.to_owned()
            }
            fn pull_source(&self, _: &Path) -> Result<(), KaizenError> {
                Ok(())
            }
            fn current_remote(&self, _: &Path) -> Result<Option<String>, KaizenError> {
                Ok(None)
            }
            fn init_source(&self, _: &str) -> Result<(), KaizenError> {
                Ok(())
            }
            fn apply(&self, _: bool) -> Result<(), KaizenError> {
                Ok(())
            }
            fn remove_files(
                &self,
                _: &[std::path::PathBuf],
                _: bool,
            ) -> Result<crate::chezmoi::RemoveFilesReport, KaizenError> {
                Ok(crate::chezmoi::RemoveFilesReport {
                    removed: vec![],
                    skipped: vec![],
                })
            }
            fn backup_source_dir(
                &self,
                _: &Path,
            ) -> Result<crate::chezmoi_client::SourceBackup, KaizenError> {
                unimplemented!()
            }
        }

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/chezmoi/dotfiles");
        fs.add_dir(&source);
        let chezmoidata = source.join(".chezmoidata.toml");

        // data.toml has aerospace selected (written by wizard / `kaizen variant set`).
        let kaizen_data = std::path::PathBuf::from("/kaizen/data.toml");
        fs.add_file(
            &kaizen_data,
            "layout = \"colemak\"\n[variants]\n\"tiling.wm\" = \"aerospace\"\n",
        );

        // plan.variants is EMPTY — as it would be during a plain `kaizen sync`.
        let plan = ConfigPlan {
            backend: "chezmoi".to_owned(),
            dotfiles_source: None,
            features_data: IndexMap::new(),
            settings: Default::default(),
            extra: Default::default(),
            variants: std::collections::BTreeMap::new(),
        };

        write_variant_data_to_chezmoi(
            &plan,
            &kaizen_data,
            &SourceStub(source),
            fs.as_ref(),
            &TargetOs::Darwin,
        )
        .unwrap();

        let result = fs.read_to_string(&chezmoidata).unwrap();
        assert!(
            result.contains("aerospace"),
            "chezmoidata must contain aerospace read from data.toml; got:\n{result}"
        );
        assert!(
            !result.contains("yabai"),
            "must not fall back to default when data.toml has an explicit selection"
        );
    }

    // ── export_shortcuts_to_chezmoi ────────────────────────────────────────────

    const SAMPLE_CATALOG: &str = r#"
[modifiers.darwin]
SUPER = "Cmd"
ALT   = "Opt"

[modifiers.linux]
SUPER = "Super"
ALT   = "Alt"

[shortcuts]
"projects.pick"   = { keys = ["p", "p"],                  group = "Projects", description = "Pick project" }
"pane.focus.left" = { keys = ["SUPER", "ALT", "Left"],   group = "Pane",     description = "Focus pane left" }
"#;

    const SAMPLE_CATALOG_LEGACY: &str = r#"
[modifiers.darwin]
SUPER = "Cmd"
ALT   = "Opt"

[modifiers.linux]
SUPER = "Super"
ALT   = "Alt"

[shortcuts]
"projects.pick"   = ["p", "p"]
"pane.focus.left" = ["SUPER", "ALT", "Left"]
"#;

    use std::path::Path;

    struct SourceStub(std::path::PathBuf);
    impl crate::chezmoi_client::ChezmoiClient for SourceStub {
        fn managed_files(&self) -> Result<Vec<std::path::PathBuf>, KaizenError> {
            Ok(vec![])
        }
        fn locally_modified_files(&self) -> Result<Vec<std::path::PathBuf>, KaizenError> {
            Ok(vec![])
        }
        fn source_path(&self) -> Result<Option<std::path::PathBuf>, KaizenError> {
            Ok(Some(self.0.clone()))
        }
        fn raw_source_path(&self) -> Result<Option<std::path::PathBuf>, KaizenError> {
            Ok(Some(self.0.clone()))
        }
        fn resolve_source_root(&self, e: &Path) -> std::path::PathBuf {
            e.to_owned()
        }
        fn pull_source(&self, _: &Path) -> Result<(), KaizenError> {
            Ok(())
        }
        fn current_remote(&self, _: &Path) -> Result<Option<String>, KaizenError> {
            Ok(None)
        }
        fn init_source(&self, _: &str) -> Result<(), KaizenError> {
            Ok(())
        }
        fn apply(&self, _: bool) -> Result<(), KaizenError> {
            Ok(())
        }
        fn remove_files(
            &self,
            _: &[std::path::PathBuf],
            _: bool,
        ) -> Result<crate::chezmoi::RemoveFilesReport, KaizenError> {
            Ok(crate::chezmoi::RemoveFilesReport {
                removed: vec![],
                skipped: vec![],
            })
        }
        fn backup_source_dir(
            &self,
            _: &Path,
        ) -> Result<crate::chezmoi_client::SourceBackup, KaizenError> {
            unimplemented!()
        }
    }

    fn shortcut_entry(raw: &str, id: &str) -> toml::Value {
        toml::from_str::<toml::Value>(raw)
            .expect("chezmoidata must parse")
            .get("kaizen")
            .and_then(|v| v.get("shortcuts"))
            .and_then(|v| v.get(id))
            .cloned()
            .unwrap_or_else(|| panic!("[kaizen.shortcuts.{id}] must be present"))
    }

    fn setup_catalog(fs: &crate::fs::mem::MemFileSystem, source: &std::path::Path) {
        let kaizen_dir = source.join("kaizen");
        fs.add_dir(&kaizen_dir);
        fs.add_file(&kaizen_dir.join("keybindings.toml"), SAMPLE_CATALOG);
    }

    fn setup_catalog_legacy(fs: &crate::fs::mem::MemFileSystem, source: &std::path::Path) {
        let kaizen_dir = source.join("kaizen");
        fs.add_dir(&kaizen_dir);
        fs.add_file(&kaizen_dir.join("mnemonics.toml"), SAMPLE_CATALOG_LEGACY);
    }

    #[test]
    fn export_shortcuts_writes_resolved_tokens() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        setup_catalog(&fs, &source);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();

        let focus = shortcut_entry(&raw, "pane.focus.left");
        let arr = focus.as_array().expect("must be array");
        assert_eq!(arr[0].as_str(), Some("Cmd"), "SUPER → Cmd on darwin");
        assert_eq!(arr[1].as_str(), Some("Opt"), "ALT → Opt on darwin");
        assert_eq!(arr[2].as_str(), Some("Left"), "literal unchanged");

        let pick = shortcut_entry(&raw, "projects.pick");
        let arr_p = pick.as_array().expect("must be array");
        assert_eq!(arr_p[0].as_str(), Some("p"), "literal p unchanged");
        assert_eq!(arr_p[1].as_str(), Some("p"));
    }

    #[test]
    fn export_shortcuts_linux_modifiers() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        setup_catalog(&fs, &source);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Linux,
            None,
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();
        let focus = shortcut_entry(&raw, "pane.focus.left");
        let arr = focus.as_array().expect("must be array");
        assert_eq!(arr[0].as_str(), Some("Super"), "SUPER → Super on linux");
        assert_eq!(arr[1].as_str(), Some("Alt"), "ALT → Alt on linux");
        assert_eq!(arr[2].as_str(), Some("Left"));
    }

    #[test]
    fn export_shortcuts_literal_keys_unchanged() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        setup_catalog(&fs, &source);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();
        let pick = shortcut_entry(&raw, "projects.pick");
        let arr = pick.as_array().expect("must be array");
        assert_eq!(arr[0].as_str(), Some("p"));
        assert_eq!(arr[1].as_str(), Some("p"));
    }

    #[test]
    fn export_shortcuts_preserves_unrelated_keys() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        setup_catalog(&fs, &source);

        let chezmoidata_path = source.join(".chezmoidata.toml");
        fs.add_file(
            &chezmoidata_path,
            "username = \"alice\"\n[tiling]\nwm = \"komorebi\"\n[kaizen.other]\nkeep = \"yes\"\n",
        );

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        )
        .unwrap();

        let raw = fs.read_to_string(&chezmoidata_path).unwrap();
        let val: toml::Value = toml::from_str(&raw).expect("must parse");
        assert_eq!(
            val.get("username").and_then(|v| v.as_str()),
            Some("alice"),
            "top-level key preserved"
        );
        assert_eq!(
            val.get("tiling")
                .and_then(|v| v.get("wm"))
                .and_then(|v| v.as_str()),
            Some("komorebi"),
            "tiling.wm preserved"
        );
        assert_eq!(
            val.get("kaizen")
                .and_then(|v| v.get("other"))
                .and_then(|v| v.get("keep"))
                .and_then(|v| v.as_str()),
            Some("yes"),
            "kaizen.other.keep preserved alongside kaizen.shortcuts"
        );
        let _ = shortcut_entry(&raw, "pane.focus.left");
    }

    #[test]
    fn export_shortcuts_missing_file_is_noop() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        )
        .unwrap();

        assert!(
            !fs.exists(&source.join(".chezmoidata.toml")),
            ".chezmoidata.toml must not be created when catalog is absent"
        );
    }

    #[test]
    fn export_shortcuts_invalid_chezmoidata_returns_error() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        setup_catalog(&fs, &source);

        let chezmoidata_path = source.join(".chezmoidata.toml");
        fs.add_file(&chezmoidata_path, "not [ valid toml =");
        let original = fs.read_to_string(&chezmoidata_path).unwrap();

        let result = export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        );

        assert!(
            matches!(result, Err(KaizenError::ConfigParse { .. })),
            "expected ConfigParse; got: {result:?}"
        );
        assert_eq!(
            fs.read_to_string(&chezmoidata_path).unwrap(),
            original,
            ".chezmoidata.toml must not be modified on parse error"
        );
    }

    #[test]
    fn export_shortcuts_fallback_reads_mnemonics() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        // Only legacy file present — no keybindings.toml
        setup_catalog_legacy(&fs, &source);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();
        let focus = shortcut_entry(&raw, "pane.focus.left");
        let arr = focus.as_array().expect("must be array");
        assert_eq!(
            arr[0].as_str(),
            Some("Cmd"),
            "fallback: SUPER → Cmd on darwin"
        );
    }

    const OVERLAY_CATALOG: &str = r#"
[shortcuts]
"nav.down"  = ["j"]
"nav.up"    = ["k"]
"nav.right" = ["l"]
"plain"     = ["x", "y"]

[layout.colemak.shortcuts]
"nav.down"  = ["n"]
"nav.up"    = ["e"]
"nav.right" = ["i"]

[layout.colemak.extra]
"nav.add" = ["z"]
"#;

    fn setup_overlay_catalog(fs: &crate::fs::mem::MemFileSystem, source: &std::path::Path) {
        let kaizen_dir = source.join("kaizen");
        fs.add_dir(&kaizen_dir);
        fs.add_file(&kaizen_dir.join("keybindings.toml"), OVERLAY_CATALOG);
    }

    #[test]
    fn export_shortcuts_colemak_overlay_overrides_base() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        setup_overlay_catalog(&fs, &source);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            Some("colemak"),
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();
        let nav_down = shortcut_entry(&raw, "nav.down");
        let arr = nav_down.as_array().expect("must be array");
        assert_eq!(
            arr[0].as_str(),
            Some("n"),
            "colemak overlay overrides base j → n"
        );
    }

    #[test]
    fn export_shortcuts_no_layout_uses_base() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        setup_overlay_catalog(&fs, &source);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();
        let nav_down = shortcut_entry(&raw, "nav.down");
        let arr = nav_down.as_array().expect("must be array");
        assert_eq!(arr[0].as_str(), Some("j"), "no layout → base qwerty value");
    }

    #[test]
    fn export_shortcuts_overlay_adds_new_key() {
        // OVERLAY_CATALOG has [layout.colemak.extra] but we test [shortcuts] overlay
        // using a catalog where overlay introduces a key absent from base.
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        let catalog = r#"
[shortcuts]
"existing" = ["a"]

[layout.colemak.shortcuts]
"new.key" = ["b"]
"#;
        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        let kaizen_dir = source.join("kaizen");
        fs.add_dir(&kaizen_dir);
        fs.add_file(&kaizen_dir.join("keybindings.toml"), catalog);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            Some("colemak"),
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();
        let new_key = shortcut_entry(&raw, "new.key");
        let arr = new_key.as_array().expect("must be array");
        assert_eq!(
            arr[0].as_str(),
            Some("b"),
            "overlay adds new key absent from base"
        );
    }

    #[test]
    fn export_shortcuts_lowercase_token_passes_through() {
        use crate::fs::mem::MemFileSystem;
        use std::sync::Arc;

        // Catalog with only lowercase tokens — no UPPERCASE that requires layout.
        let catalog = r#"
[shortcuts]
"plain" = ["x", "y"]
"leader.seq" = ["g", "g"]
"#;
        let fs = Arc::new(MemFileSystem::new());
        let source = std::path::PathBuf::from("/src/dotfiles");
        fs.add_dir(&source);
        let kaizen_dir = source.join("kaizen");
        fs.add_dir(&kaizen_dir);
        fs.add_file(&kaizen_dir.join("keybindings.toml"), catalog);

        export_shortcuts_to_chezmoi(
            &SourceStub(source.clone()),
            fs.as_ref(),
            &TargetOs::Darwin,
            None,
        )
        .unwrap();

        let raw = fs
            .read_to_string(&source.join(".chezmoidata.toml"))
            .unwrap();
        let plain = shortcut_entry(&raw, "plain");
        let arr = plain.as_array().expect("must be array");
        assert_eq!(arr[0].as_str(), Some("x"), "literal x unchanged");
        assert_eq!(arr[1].as_str(), Some("y"), "literal y unchanged");
    }
}
