default:
    just --list

sync:
    kaizen sync

update:
    kaizen update

self-update:
    kaizen self-update

bump:
    kaizen bump

capture:
    kaizen capture

status:
    kaizen status

layout layout="":
    ~/.config/scripts/layout {{ layout }}

fedora-upgrade VERSION="44":
    sudo dnf system-upgrade download --releasever={{VERSION}} --allowerasing
    sudo dnf system-upgrade reboot

apply:
    chezmoi apply
