;;; xonsh-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from xonsh-mode.el

(autoload 'xonsh-mode "xonsh-mode"
"Major mode for xonsh, derived from Python mode.
\\{xonsh-mode-map}

In addition to any hooks its parent mode `python-mode' might have run,
this mode runs the hook `xonsh-mode-hook', as the final or penultimate
step during initialization." t)
(add-to-list 'auto-mode-alist '("\\.xsh\\'" . xonsh-mode))
(add-to-list 'auto-mode-alist '("\\.xonshrc\\'" . xonsh-mode))
(add-to-list 'auto-mode-alist '("xonshrc" . xonsh-mode))
(register-definition-prefixes "xonsh-mode" '("xonsh-font-lock-keywords"))

;;; End of scraped data

(provide 'xonsh-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xonsh-mode-autoloads.el ends here
