[meta]
description = "Collection of best AI agents, dependencies, tools, agents and skills"

[mise.tools]
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:skills" = "latest"
"npm:context-mode" = "latest"


# Pi dependencies
"npm:pi-link" = "latest"

