;;; vue-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from vue-ts-mode.el

(autoload 'vue-ts-mode "vue-ts-mode"
"Major mode for editing Vue templates, powered by tree-sitter.

In addition to any hooks its parent mode `prog-mode' might have run,
this mode runs the hook `vue-ts-mode-hook', as the final or
penultimate step during initialization.

\\{vue-ts-mode-map}" t)
(register-definition-prefixes "vue-ts-mode" '("vue-ts-mode-"))

;;; End of scraped data

(provide 'vue-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vue-ts-mode-autoloads.el ends here
