;;; flymake-stylelint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from flymake-stylelint.el

(autoload 'flymake-stylelint-enable "flymake-stylelint"
"Enable Flymake and add flymake-stylelint as a buffer-local Flymake backend." t)
(register-definition-prefixes "flymake-stylelint" '("flymake-stylelint-"))

;;; End of scraped data

(provide 'flymake-stylelint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-stylelint-autoloads.el ends here
