[tools]
"npm:typescript" = "6.0.3"
"npm:prettier" = "3.9.6"
"npm:@angular/cli" = "22.1.7"
"npm:@angular/language-server" = "22.1.5"
"npm:@vue/language-server" = "2.2.12"
"npm:eslint" = "10.9.1"
"npm:stylelint" = "17.15.0"
"npm:npm-check-updates" = "23.1.0"
